import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  containerWrap: {
    minHeight: '100%',
    backgroundColor: '#1fa75c',
  },
  container: {
    backgroundColor: '#1fa75c',
    paddingTop: 20,
    paddingBottom: 20,
    paddingLeft: 15,
    paddingRight: 15,
  },
  list: {
    flex: 1,
    justifyContent: 'center',
  },
  btnWrap: {
    backgroundColor: '#ff8e57',
    paddingTop: 15,
    paddingBottom: 15,
    borderRadius: 5,
    marginLeft: 7,
    marginRight: 7,
    marginTop: 5,
    marginBottom: 5,
  },
  btnText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 18,
    fontFamily: 'Almarai-Bold',
  },
  inputWrap: {
    marginBottom: 20,
    marginLeft: 7,
    marginRight: 7,
  },
  label: {
    color: '#eee',
    fontFamily: 'Almarai-Regular',
    marginBottom: 10,
  },
  input: {
    backgroundColor: '#1d9b55',
    borderRadius: 5,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 15,
    paddingRight: 15,
    color: '#fff',
    textAlign: 'right',
    fontFamily: 'Almarai-Regular',
    fontSize: 16,
  },
  result: {
    marginTop: 5,
    color: '#fff',
    fontFamily: 'Almarai-Regular',
    textAlign: 'center',
    fontSize: 18,
  },
  listItemWrap: {
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 20,
    paddingRight: 20,
    marginLeft: 7,
    marginRight: 7,
    marginTop: 5,
    marginBottom: 5,
    backgroundColor: '#1d9b55',
    borderRadius: 5,
  },
  listItemText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Almarai-Regular',
  },
  selectWrap: {
    backgroundColor: '#1d9b55',
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 5,
    display: 'flex',
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  selectArrow: {
    width: 15,
    height: 15,
    marginLeft: 20,
  },
  selectLabel: {
    color: '#fff',
    textAlign: 'right',
    fontSize: 18,
    fontFamily: 'Almarai-Regular',
  },
  selectItemsWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '100%',
    backgroundColor: '#eee',
    zIndex: 2,
    borderRadius: 5,
  },
  selectItem: {
    padding: 15,
  },
  selectItemLabel: {
    fontFamily: 'Almarai-Bold',
  },
  title: {
    color: '#fff',
    fontFamily: 'Almarai-Bold',
    fontSize: 18,
    padding: 10,
  },
});
